### ISSUE TITLE
TODO/FIXME Count 16

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-permission#23]
- [ ] FIXME: use new bedrock-identity format
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [test/mocha/mock.data.js:14](https://github.com/digitalbazaar/bedrock-permission/blob/master/test/mocha/mock.data.js#L14)
       Dave Longley commented 2 years ago

  - [ ] FIXME: remove extra promisify once new API is in place
       Commit: (77ffc32) Fix linting errors.
       File:  [test/mocha/01-api.js:110](https://github.com/digitalbazaar/bedrock-permission/blob/master/test/mocha/01-api.js#L110)
       Matthew Collier commented 2 months ago

  - [ ] FIXME: remove extra promisify once new API is in place
       Commit: (77ffc32) Fix linting errors.
       File:  [test/mocha/01-api.js:93](https://github.com/digitalbazaar/bedrock-permission/blob/master/test/mocha/01-api.js#L93)
       Matthew Collier commented 2 months ago

  - [ ] FIXME: remove extra promisify once new API is in place
       Commit: (77ffc32) Fix linting errors.
       File:  [test/mocha/01-api.js:80](https://github.com/digitalbazaar/bedrock-permission/blob/master/test/mocha/01-api.js#L80)
       Matthew Collier commented 2 months ago

  - [ ] FIXME: remove extra promisify once new API is in place
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [test/mocha/01-api.js:62](https://github.com/digitalbazaar/bedrock-permission/blob/master/test/mocha/01-api.js#L62)
       Dave Longley commented 2 years ago

  - [ ] TODO: including the actor in the options doesn't seem to be the cleanest
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:636](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L636)
       Dave Longley commented 2 years ago

  - [ ] TODO: use named params
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:615](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L615)
       Dave Longley commented 2 years ago

  - [ ] TODO: use named params, split `tableOrActor` into `table` and `actor`
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:550](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L550)
       Dave Longley commented 2 years ago

  - [ ] TODO: support default identifiers for properties?
       Commit: (408fdfc) Permission updates.
       File:  [lib/permission.js:376](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/permission.js#L376)
       Dave Longley commented 6 years ago

  - [ ] TODO: implement this as a database query
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:222](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L222)
       Dave Longley commented 2 years ago

  - [ ] TODO: use `meta.status`
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:192](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L192)
       Dave Longley commented 2 years ago

  - [ ] TODO: update API to use patch and sequence
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:173](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L173)
       Dave Longley commented 2 years ago

  - [ ] TODO: optimize with projection
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:131](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L131)
       Dave Longley commented 2 years ago

  - [ ] TODO: update API to throw `DuplicateError` BedrockError
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:65](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L65)
       Dave Longley commented 2 years ago

  - [ ] TODO: update API to use named parameters
       Commit: (2a8cf62) Update internals to use async+await.
       File:  [lib/index.js:61](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L61)
       Dave Longley commented 2 years ago

  - [ ] FIXME: this is because _checkPermission is not at the top of the file
       Commit: (77ffc32) Fix linting errors.
       File:  [lib/index.js:6](https://github.com/digitalbazaar/bedrock-permission/blob/master/lib/index.js#L6)
       Matthew Collier commented 2 months ago
